# Generated by Django 2.1.7 on 2019-02-19 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Creator Name')),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
