# Generated by Django 2.1.7 on 2019-02-24 14:05

import creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to=creators.models.upload_path),
        ),
    ]
