# Generated by Django 2.1.7 on 2019-02-19 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('bg_image', models.ImageField(upload_to='bg-images')),
                ('description', models.TextField()),
                ('img_1', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_2', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_3', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_4', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_5', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_6', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_7', models.ImageField(blank=True, upload_to='presets-images')),
                ('img_8', models.ImageField(blank=True, upload_to='presets-images')),
                ('is_published', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='creators.Author')),
            ],
        ),
    ]
