# Generated by Django 2.1.7 on 2019-02-24 14:05

from django.db import migrations, models
import presets.models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='down_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preset',
            name='bg_image',
            field=models.ImageField(upload_to=presets.models.upload_preset_bg_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_1',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_2',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_3',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_4',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_5',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_6',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_7',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
        migrations.AlterField(
            model_name='preset',
            name='img_8',
            field=models.ImageField(blank=True, upload_to=presets.models.upload_preset_image_path),
        ),
    ]
